### ISSUE TITLE
Running time of DDMOP

### ISSUE THREAD

**Issue by ghost** [HandingWang/DDMOP#1]
I have run DDMOP1 and I am not able to get objective values of initial solutions because it is taking much time to get objective values. Would you please provide us  approximate running time per solution for each of the problems in DDMOPs. Are all the problems unconstrained problem? Thank you.

**Comment by ylddd** [comment]
Sorry to bother,  when I run the command “[lower, upper] = DDMOPi('boundary',);”  in the file of readme.txt, I get the following error: "Error: Parentheses or square brackets are asymmetrical or abnormal." Can you run  it successfully? Looking for forward to your answer, thank you.

**Comment by ylddd** [comment]
> I have run DDMOP1 and I am not able to get objective values of initial solutions because it is taking much time to get objective values. Would you please provide us approximate running time per solution for each of the problems in DDMOPs. Are all the problems unconstrained problem? Thank you.

Sorry to bother, when I run the command “[lower, upper] = DDMOPi('boundary',);” in the file of readme.txt, I get the following error: "Error: Parentheses or square brackets are asymmetrical or abnormal." Can you run it successfully? Looking for forward to your answer, thank you.

**Comment by HandingWang** [comment]
Each evaluation takes 6-15 secs.
